### PR TITLE
Basic transition to multiple choice

### PR DESCRIPTION
**Pull request by erikbarzdukas**
Users interact with the game through buttons now, which represent multiple choice options for questions.

### CODE REVIEW

**Comment by erikbarzdukas** [comment]
fixes #2

**Comment by erikbarzdukas** [comment]
Accidental second grouping into same pull request. Latter grouping fixes bug #8.

**Comment by erikbarzdukas** [comment]
Commit 1dcb8d3 also improves the scoring algorithm re #7

**Comment by fractal5** [comment]
Looks good.

**Pull request merged**
